### ISSUE TITLE
Don't use text-field elements in the component configurations

### ISSUE THREAD

**Issue by knudmoeller** [silk-framework/silk#10]
![7848b06a328b8b31d876c6ad34897bee](https://cloud.githubusercontent.com/assets/1128115/3383531/18e3d15e-fc4c-11e3-9ffe-301581c867fd.jpeg)
- instead, use simple HTML labels (like the component name)

**Comment by andreas-schultz** [comment]
Outdated. This addresses the already removed legacy UI.
