### ISSUE TITLE
About adding files into datasets

### ISSUE THREAD

**Issue by jtrillos** [silk-framework/silk#182]
Hi, 
I do not understand where to add the csv file in the Silk Workbench...
It is said that I need to add it in `/root/.silk/workspace/<name-project>/resources/<file>` but i can not access to the `root`.

Can someone help me?

PS. I am executing it in the docker

Thanks

**Comment by andreas-schultz** [comment]
You can upload file resources on the workspace page via the 'Resources' menu.

**Comment by jtrillos** [comment]
Thanks. I works

**Comment by jakubklimek** [comment]
Actually, this works for datasets smaller than 10 MB due to the configuration of the web server not allowing us to upload larger files.

It would make more sense to have resources as part of the mounted silk workspace directory. Any reason for having resources in roots home?
