### ISSUE TITLE
Error occurs when I execute ' sbt "project workbench" run '

### ISSUE THREAD

**Issue by TheGodOfObelisk** [silk-framework/silk#268]
It seems something goes wrong when starting the workbench server.
`[error] Not a valid project ID: workbench
[error] project workbench
`
How can I fix it? Thanks.

**Comment by TheGodOfObelisk** [comment]
Sorry, it is a silly question.

**Comment by dev-dsp** [comment]
How did you fix that?

**Comment by EnsiyehRaoufi** [comment]
> Sorry, it is a silly question.

Could you tell me how did you fix it? I have this silly question, too.

**Comment by EnsiyehRaoufi** [comment]
> How did you fix that?

Could you tell me how did you fix it?

**Comment by TheGodOfObelisk** [comment]
> > How did you fix that?
> 
> Could you tell me how did you fix it?

Sorry. I can't remember. Sorry.
