### ISSUE TITLE
Dataset metadata are not displayed in the editor pane

### ISSUE THREAD

**Issue by svatek** [silk-framework/silk#30]
When I try to use the latest version, 2.6.0 (Windows), I am not able to see the metadata of source/target datasets in the editor left pane:
![silk_rule](https://cloud.githubusercontent.com/assets/6616138/5199129/7b07e7c2-7559-11e4-8e51-e882be3b95f3.jpg)
These metadata (source names and restrictions) are only visible in the workbench overview:
![silk_project](https://cloud.githubusercontent.com/assets/6616138/5199284/cc76a62e-755a-11e4-9869-722010607cb5.jpg)
They also seem OK in the XML project export.

**Comment by robertisele** [comment]
The dataset names are now displayed in the editor
