### ISSUE TITLE
Learning Tab not visible

### ISSUE THREAD

**Issue by alimasri** [silk-framework/silk#34]
Hi Guys,
I am using Silk version 2.6.0, the learn tab is not showing when I try to open a linkage rule. I tried to modify the value of workbench.tabs.learn in the application.conf into true, but yet this didn't solve my problem.
Can anyone help me please.
Thanks in advance.

**Comment by robertisele** [comment]
In Version 2.7.0 the learning tab can be activated by setting workbench.tabs.learn to true. It is disabled by default as it is still work in progress.
