### ISSUE TITLE
troubleshooting in downloading and installing silk 

### ISSUE THREAD

**Issue by gloucklegnou** [silk-framework/silk#36]
I wanted to experiment with Silk, I went to the silk website download tab (http://silk-framework.com/download) that says:

"All stable releases can be [downloaded](http://silk.wbsg.de/releases/)".

But when  I'm clicking on  the "downloaded" link the underlying url http://silk.wbsg.de/releases/ automatically redirects me to the silk http://silk-framework.com/.  

Is there an easy way to download the latest version of Silk ? Otherwise, do I have to clone the silk project ? In this case how do I recompile it to have an executable version of silk (windows 7 64) ?

**Comment by jmvanel** [comment]
Hi glou

You can download the zip from github,
https://github.com/silk-framework/silk/releases

then run stb ( http://www.scala-sbt.org/ )
then inside sbt :
project workbench
run


2015-05-27 15:41 GMT+02:00 gloucklegnou <notifications@github.com>:

> I wanted to experiment with Silk, I went to the silk website download tab (
> http://silk-framework.com/download) that says:
>
> "All stable releases can be downloaded <http://silk.wbsg.de/releases/>".
>
> But when I'm clicking on the "downloaded" link the underlying url
> http://silk.wbsg.de/releases/ iautomatically redirects me to the silk
> http://silk-framework.com/.
>
> Is there an easy way to download the latest version of Silk ? Otherwise,
> do I have to clone the silk project ? In this case how do I recompile it to
> have an executable version of silk (windows 7 64) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silk-framework/silk/issues/36>.
>



-- 
Jean-Marc Vanel
Déductions SARL - Consulting, services, training,
Rule-based programming, Semantic Web
http://deductions-software.com/
+33 (0)6 89 16 29 52
Twitter: @jmvanel , @jmvanel_fr ; chat: irc://irc.freenode.net#eulergui

**Comment by robertisele** [comment]
The download link became invalid when the Silk homepage has been moved to http://silk-framework.com. I have fixed the link to the Silk releases, which are now hosted on Github.
