### ISSUE TITLE
Is there a way to actually retreive the output of the link generation process?

### ISSUE THREAD

**Issue by Maatary** [silk-framework/silk#42]
Hi, 

I try to read here and there, and honestly not easy: don't you have one simple guide that one should follow to retreive the result of the link generation process (workbench). This is the main point of the software, getting the links at the end, and this functionality is simply not obvious at all. 

I am using the latest release. I spend a full day on it, and i can't find a way to retrieve the output. 

I am never able to specify an output file, other than the one from the source and target. 

It appear that when i choose the target file/endpoint to be also the  output, then i get a plugin not present bug. 

This is deeply confusing. 

Please a quick help here would be great.

**Comment by robertisele** [comment]
Fixed in 2.7.0. RC, which also includes an example of a working configuration that writes to a file.
