### ISSUE TITLE
Bump JDK version to get TLS 1.3 support

### ISSUE THREAD

**Issue by jakubklimek** [silk-framework/silk#445]
In the current docker image, TLS 1.3 is not supported (e.g. when SILK is querying remote endpoints), due to the old JDK 1.8_u151 being used. This is prohibited, as using TLSv1.3 only is becoming more common these days, as this is also the setting generated for Modern browsers by https://ssl-config.mozilla.org/.

TLS v1.3 is supported in Java 11 and it seems it was also [backported to Java 8](https://stackoverflow.com/a/62956195/12972160).

**Comment by andreas-schultz** [comment]
Thanks for the hint. I will change it to use the latest OpenJDK 8 version. #449
