### ISSUE TITLE
Workbench REST API returns 404

### ISSUE THREAD

**Issue by mmkrystek** [silk-framework/silk#47]
For silk versions tagged as release-2.6.1 GET http://localhost:9000/api/workspace returns 404 where, according to the documentation https://www.assembla.com/spaces/silk/wiki/REST_API, it should return JSON that describes the projects in the workspace.

**Comment by robertisele** [comment]
The documentation at Assembla is outdated as indicated at the Wiki home page. The documentation of the REST API is available here: https://github.com/silk-framework/silk/blob/master/doc/RestInterface.md

Please upgrade to Release 2.7.0 RC1, which should work as expected
