### ISSUE TITLE
Error: SourceDataset/RestrictTo does not allow searching for time

### ISSUE THREAD

**Issue by PeteBlanchard** [silk-framework/silk#49]
Was trying to create a restriction to search for specific types that had a time after "2012-04-12T12:00:00Z" in order to limit the number of results that came back (vice getting them all, then filtering).
Tried for both workbench and singlemachine, each threw an error the prefix "2010-04-12T12:00:" (singlemachine) or '"2012-04-12T12:00:00Z"^^xsd:' (workbench) was not defined.
Example Workbench RestrictTo:
{  ?a rdf:type myP:myType .
   ?a myP:myDateTime "2012-04-12T12:00:00Z"^^xsd:dateTime . }

For the singlemachine I made it verbose like I saw in the written XML files of the workbench (handtyped here, please forgive any typos):
{  ?a &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#type&gt; &lt;http://example.org/myOnt#myType&gt; .
   ?a &lt;http://example.org/myOnt#myDateTime&gt; "2012-04-12T12:00:00Z"^^&lt;http://www.w3.org/2001/XMLSchema#dateTime&gt; . }

Where my date had both specified.
Also, tried to specify as a prefix, but received error for the ":" character (as expected).

**Comment by robertisele** [comment]
The bug concerning the incorrect parsing of the xsd type has been fixed in master. Could you please retest if this fixes your issue?

**Comment by PeteBlanchard** [comment]
Tried building with:

  sbt "project workbench" dist

then extracted the "silk-workbench/target/universal/workbench-2.7.0.SNAPSHOT" to a new dir (on RHEL6, running openJDK 1.7)

Then, in terminal, 'bin/workbench", but it is complaining about a configuration exception for "application.conf", "application.json" and "application.properties" not being found on the classpath, but I don't see them in any of the silk-master sub-directories (either).

**Comment by robertisele** [comment]
Sorry, there has been a problem, as application.conf has been renamed. Please pull and try again

**Comment by PeteBlanchard** [comment]
Yep, that fixed it.  Thanks!
