### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by uno544** [silk-framework/silk#524]
![1640592845934](https://user-images.githubusercontent.com/27668263/147451571-325bcf41-9919-40d6-b00a-7c7f8089b6ff.jpg)
Hi I've been having trouble installing SILK no matter what I do, the attached image is the error I am getting. 
Also I am confused about the Yarn for React/JavaScript build pipeline (>= 1.3) per-requisite, because the latest Yarn version I can find is 1.22.17 only
Is there something I am missing? Any help is appreciated, thanks in advance

**Comment by andreas-schultz** [comment]
Hi, there should also be (stderr) output of the yarn process somewhere in the log, alternatively you can run `yarn webpack-dev-build` directly in the `silk-react-components` directory which should have a nicer error output.
