### ISSUE TITLE
Supervised Learning config format

### ISSUE THREAD

**Issue by alberto-ruiz4** [silk-framework/silk#565]
Hello,

I'm testing the REST API to use the SupervisedLearning activity to learn links from a population of reference links.

Currently, I'm trying to send POST requests to the resources located at:

http://localhost:9000/workspace/projects/movies/tasks/movies/activities/SupervisedLearning/config

and

http://localhost:9000/workspace/projects/movies/tasks/movies/activities/SupervisedLearning/startBlocking

But in the first one I get this response:
{
    "title": "Bad Request",
    "detail": "No config supplied",
    "cause": null
}

And the second one generates this result after completion: 

LearningResult(0,0,Population(List()),recall=NaN precision=0.000 f1=0.000 mcc=0.000 score=0.000,recall=NaN precision=0.000 f1=0.000 mcc=0.000 score=0.000,)

I guess some additional configuration is needed to start the process. Could you provide an example of the parameters expected by this method?

Thanks.

**Comment by andreas-schultz** [comment]
Hi Alberto,

sorry for the late reply.

The /config endpoint is deprecated and should not be used anymore. Instead you can send a config directly with the /startBlocking request (form-urlencoded).
