### ISSUE TITLE
'About' tab in navbar causes JS error

### ISSUE THREAD

**Issue by knudmoeller** [silk-framework/silk#64]
In the MDL version of Silk, the 'About' tab opens a dialog but has no href attribute. This causes two problems:
- Uncaught TypeError: Cannot read property 'classList' of null(anonymous function) @ material.js:2725
- 'About' tab is then highlighted, regardless of which tab we are actually on.

Proposed solution: 'About' should either be an actual tab (not a dialog), or not be included in the tab bar at all.

**Comment by andreas-schultz** [comment]
Outdated
