### ISSUE TITLE
z-index problem with JSPlumb and MDL tooltips

### ISSUE THREAD

**Issue by knudmoeller** [silk-framework/silk#65]
In the editor, the new MDL tooltips are partially obscured by parts of the JSPlumb UI.

Proposed solution: upgrade JSPlumb and hope that fixes it.
<img width="312" alt="screen shot 2016-07-21 at 15 44 37" src="https://cloud.githubusercontent.com/assets/1128115/17024962/1d5f7086-4f5a-11e6-88d0-87804b265081.png">

**Comment by andreas-schultz** [comment]
Outdated
