### ISSUE TITLE
Current version compilation fails with Java7, compiles fine with Java8

### ISSUE THREAD

**Issue by isktech** [silk-framework/silk#69]
Hi, just downloaded and built latest version but compilation failed with Java7:

[error] /usr/local/silk-master/silk-workspace/src/main/scala/org/silkframework/workspace/activity/TaskActivity.scala:75: value getTypeName is not a member of java.lang.reflect.Type
[error]     val activityInterface = activityType.getGenericInterfaces.find(_.getTypeName.startsWith(classOf[Activity[_]].getName)).get.asInstanceOf[ParameterizedType]
[error]                                                                      ^
[error] one error found
[error] (workspace/compile:compileIncremental) Compilation failed

Compiles and runs just fine with Java8 :)

**Comment by robertisele** [comment]
The minimum required version of Java has been updated to Java 8, without updating the readme. It's updated now, thanks for the heads-up.
