### ISSUE TITLE
Problems with running the repo locally

### ISSUE THREAD

**Issue by shreyas1599** [silk-framework/silk#729]
When trying to do `./sbt "project workbench" run` locally from the project root - I get this error:

`error An unexpected error occurred: "https://artifactory.eccenca.com/api/npm/npm/scheduler/-/scheduler-0.19.1.tgz: Request failed \"401 Unauthorized\"".`

Seems like it's trying to download some npm packages from a URL I don't have access to. 

There's also a react-flow-renderer warning (but think only the above is breaking the build) - 
`warning workspace-aggregator-3a233ad3-8ec1-4cb9-b7ff-0f0770af8c72 > workspace-ui > @eccenca/gui-elements > react-flow-renderer@10.3.17: react-flow-renderer has been renamed to reactflow, please use this package from now on https://reactflow.dev/docs/guides/migrate-to-v11/
`

Any help is appreciated in being able to run this locally.

**Comment by andreas-schultz** [comment]
It is runnning `yarn --frozen-lockfile` internally, so the URLs to fetch the dependencies is not updated to a public repository.

As a workaroung can you try running `yarn` first and then repeat the command?

**Comment by shreyas1599** [comment]
@andreas-schultz thanks. I ran `yarn` from the root but still get the same error. It's still trying to access the private repository Should I run it from a specific directory?

**Comment by shreyas1599** [comment]
@andreas-schultz great thanks. Works.
